[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#1E90FF"
backgroundColor = "#0a0a1a"
secondaryBackgroundColor = "#111133"
textColor = "#00ffff"
